"""Driver registration and lookup.

Built-in drivers register themselves with `@register_driver(kind, type)`
at import time (see the bottom of e.g. drivers/tuya/cover.py). A
config.yaml entry like `{kind: cover, type: tuya_curtain_switch, ...}` is
resolved back to that factory here.

To add a new driver you do not edit this file at all: drop a new module
under `localhome/drivers/`, decorate its factory function, and reference
its `type` name from config.yaml - `load_builtin_drivers()` below
discovers it automatically by walking the drivers package.
"""
from __future__ import annotations

import importlib
import pkgutil
from typing import Any, Callable

_FACTORIES: dict[tuple[str, str], Callable[[dict], Any]] = {}
_loaded = False


def register_driver(kind: str, type_name: str):
    """Class/function decorator: register a driver factory for `kind`/`type_name`."""

    def decorator(factory):
        key = (kind, type_name)
        if key in _FACTORIES:
            raise ValueError(f"Duplicate driver registration for {key!r}")
        _FACTORIES[key] = factory
        return factory

    return decorator


def load_builtin_drivers() -> None:
    """Import every module under localhome.drivers so its @register_driver
    calls run. Safe to call more than once."""
    global _loaded
    if _loaded:
        return
    _loaded = True
    import localhome.drivers as drivers_pkg

    for module_info in pkgutil.walk_packages(drivers_pkg.__path__, prefix="localhome.drivers."):
        importlib.import_module(module_info.name)


def create(kind: str, type_name: str, options: dict) -> list:
    """Instantiate the driver(s) for one config.yaml integration entry.

    A factory may return a single driver or a list - Tuya drivers fan out
    one instance per matching entry in their devices_file, since one LAN
    scan/wizard dump commonly holds several physical devices of the same
    kind (e.g. five roller shutters).
    """
    load_builtin_drivers()
    key = (kind, type_name)
    factory = _FACTORIES.get(key)
    if factory is None:
        available = sorted(f"{k}/{t}" for k, t in _FACTORIES)
        raise ValueError(
            f"No driver registered for kind={kind!r} type={type_name!r}. "
            f"Available kind/type combinations: {available}"
        )
    result = factory(options)
    return result if isinstance(result, list) else [result]


def known_drivers() -> list[tuple[str, str]]:
    load_builtin_drivers()
    return sorted(_FACTORIES)
